create table deck_share_codes (
    id bigint generated by default as identity primary key,
    deck_id bigint not null unique,
    code varchar(16) not null unique,
    created_at timestamp not null,
    constraint fk_deck_share_codes_deck foreign key (deck_id) references decks(id) on delete cascade
);

create index idx_deck_share_codes_code on deck_share_codes(code);
