create table classrooms (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    name varchar(160) not null,
    description varchar(1000),
    invite_code varchar(16) not null unique,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_classrooms_owner foreign key (owner_id) references app_users(id) on delete cascade
);

create table classroom_members (
    id bigint generated by default as identity primary key,
    classroom_id bigint not null,
    user_id bigint not null,
    role varchar(30) not null,
    joined_at timestamp not null,
    constraint fk_classroom_members_classroom foreign key (classroom_id) references classrooms(id) on delete cascade,
    constraint fk_classroom_members_user foreign key (user_id) references app_users(id) on delete cascade,
    constraint uq_classroom_members_classroom_user unique (classroom_id, user_id)
);

create table classroom_decks (
    id bigint generated by default as identity primary key,
    classroom_id bigint not null,
    deck_id bigint not null,
    added_at timestamp not null,
    constraint fk_classroom_decks_classroom foreign key (classroom_id) references classrooms(id) on delete cascade,
    constraint fk_classroom_decks_deck foreign key (deck_id) references decks(id) on delete cascade,
    constraint uq_classroom_decks_classroom_deck unique (classroom_id, deck_id)
);

create index idx_classrooms_invite_code on classrooms(invite_code);
create index idx_classrooms_owner_id on classrooms(owner_id);
create index idx_classroom_members_user_id on classroom_members(user_id);
create index idx_classroom_members_classroom_id on classroom_members(classroom_id);
create index idx_classroom_decks_deck_id on classroom_decks(deck_id);
