create table learn_progress (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    vocab_item_id bigint not null,
    mastered boolean not null default false,
    correct_attempts integer not null default 0,
    incorrect_attempts integer not null default 0,
    last_practiced_at timestamp,
    mastered_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_learn_progress_user foreign key (user_id) references app_users(id) on delete cascade,
    constraint fk_learn_progress_vocab_item foreign key (vocab_item_id) references vocab_items(id) on delete cascade,
    constraint uq_learn_progress_user_vocab unique (user_id, vocab_item_id)
);

create index idx_learn_progress_user_id on learn_progress(user_id);
create index idx_learn_progress_vocab_item_id on learn_progress(vocab_item_id);

insert into learn_progress (
    user_id,
    vocab_item_id,
    mastered,
    correct_attempts,
    incorrect_attempts,
    last_practiced_at,
    mastered_at,
    created_at,
    updated_at
)
select
    s.user_id,
    i.vocab_item_id,
    true,
    max(i.correct_attempts),
    max(i.incorrect_attempts),
    max(coalesce(i.last_answered_at, s.completed_at, s.updated_at)),
    max(coalesce(s.completed_at, i.last_answered_at, s.updated_at)),
    now(),
    now()
from learn_session_items i
join learn_sessions s on s.id = i.session_id
where i.stage = 'MASTERED'
group by s.user_id, i.vocab_item_id
on conflict (user_id, vocab_item_id) do update set
    mastered = true,
    correct_attempts = greatest(learn_progress.correct_attempts, excluded.correct_attempts),
    incorrect_attempts = greatest(learn_progress.incorrect_attempts, excluded.incorrect_attempts),
    last_practiced_at = greatest(
        coalesce(learn_progress.last_practiced_at, excluded.last_practiced_at),
        coalesce(excluded.last_practiced_at, learn_progress.last_practiced_at)
    ),
    mastered_at = coalesce(learn_progress.mastered_at, excluded.mastered_at),
    updated_at = now();
