create table toeic_tests (
    id bigint generated by default as identity primary key,
    slug varchar(120) not null unique,
    test_name varchar(255) not null,
    collection_name varchar(120),
    test_number integer,
    total_questions integer not null,
    duration_minutes integer not null default 120,
    created_at timestamp not null
);

create table toeic_question_groups (
    id bigint generated by default as identity primary key,
    test_id bigint not null,
    question_part varchar(40) not null,
    group_order integer not null,
    passage_text text,
    audio_transcript text,
    audio_transcript_html text,
    explanation_html text,
    constraint fk_toeic_groups_test foreign key (test_id) references toeic_tests(id) on delete cascade
);

create table toeic_group_media (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    url varchar(1000) not null,
    file_type varchar(20) not null,
    display_order integer not null default 1,
    constraint fk_toeic_media_group foreign key (group_id) references toeic_question_groups(id) on delete cascade
);

create table toeic_questions (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    test_id bigint not null,
    question_part varchar(40) not null,
    question_number integer not null,
    question_text text,
    correct_answer_label varchar(4) not null,
    constraint fk_toeic_questions_group foreign key (group_id) references toeic_question_groups(id) on delete cascade,
    constraint fk_toeic_questions_test foreign key (test_id) references toeic_tests(id) on delete cascade
);

create table toeic_answers (
    id bigint generated by default as identity primary key,
    question_id bigint not null,
    answer_label varchar(4) not null,
    content text,
    answer_order integer not null,
    is_correct boolean not null default false,
    constraint fk_toeic_answers_question foreign key (question_id) references toeic_questions(id) on delete cascade
);

create index idx_toeic_groups_test_id on toeic_question_groups(test_id);
create index idx_toeic_media_group_id on toeic_group_media(group_id);
create index idx_toeic_questions_group_id on toeic_questions(group_id);
create index idx_toeic_questions_test_part on toeic_questions(test_id, question_part);
create index idx_toeic_questions_number on toeic_questions(test_id, question_number);
create index idx_toeic_answers_question_id on toeic_answers(question_id);
