create table toeic_attempts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    test_id bigint not null,
    mode varchar(20) not null,
    part_filter varchar(40),
    total_questions integer not null,
    correct_count integer not null default 0,
    listening_correct integer not null default 0,
    reading_correct integer not null default 0,
    scaled_score integer,
    listening_score integer,
    reading_score integer,
    status varchar(20) not null,
    started_at timestamp not null,
    completed_at timestamp,
    expires_at timestamp,
    constraint fk_toeic_attempts_user foreign key (user_id) references app_users(id) on delete cascade,
    constraint fk_toeic_attempts_test foreign key (test_id) references toeic_tests(id) on delete cascade
);

create table toeic_attempt_answers (
    id bigint generated by default as identity primary key,
    attempt_id bigint not null,
    question_id bigint not null,
    selected_label varchar(4),
    correct boolean not null default false,
    answered_at timestamp not null,
    constraint fk_toeic_attempt_answers_attempt foreign key (attempt_id) references toeic_attempts(id) on delete cascade,
    constraint fk_toeic_attempt_answers_question foreign key (question_id) references toeic_questions(id) on delete cascade,
    constraint uq_toeic_attempt_answers_attempt_question unique (attempt_id, question_id)
);

create index idx_toeic_attempts_user_id on toeic_attempts(user_id);
create index idx_toeic_attempts_test_id on toeic_attempts(test_id);
create index idx_toeic_attempt_answers_attempt_id on toeic_attempt_answers(attempt_id);
