create table app_users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    display_name varchar(120) not null,
    english_level varchar(40) not null,
    learning_goal varchar(500),
    daily_goal integer not null,
    created_at timestamp not null,
    updated_at timestamp not null
);
