create table decks (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    name varchar(160) not null,
    description varchar(1000),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_decks_owner foreign key (owner_id) references app_users(id) on delete cascade
);

create index idx_decks_owner_id on decks(owner_id);
