create table vocab_items (
    id bigint generated by default as identity primary key,
    deck_id bigint not null,
    word varchar(255) not null,
    normalized_word varchar(255) not null,
    part_of_speech varchar(80),
    meaning_vi varchar(1000),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_vocab_items_deck foreign key (deck_id) references decks(id) on delete cascade,
    constraint uq_vocab_items_deck_normalized_word unique (deck_id, normalized_word)
);

create index idx_vocab_items_deck_id on vocab_items(deck_id);
