create table user_progress (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    vocab_item_id bigint not null,
    status varchar(30) not null,
    known_count integer not null default 0,
    unknown_count integer not null default 0,
    difficult_count integer not null default 0,
    last_marked_at timestamp not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_user_progress_user foreign key (user_id) references app_users(id) on delete cascade,
    constraint fk_user_progress_vocab_item foreign key (vocab_item_id) references vocab_items(id) on delete cascade,
    constraint uq_user_progress_user_vocab unique (user_id, vocab_item_id)
);

create index idx_user_progress_user_id on user_progress(user_id);
create index idx_user_progress_vocab_item_id on user_progress(vocab_item_id);
