alter table vocab_items add column ipa varchar(120);
alter table vocab_items add column pronunciation_hint varchar(500);
alter table vocab_items add column example_en varchar(1000);
alter table vocab_items add column example_vi varchar(1000);
alter table vocab_items add column topic varchar(120);
alter table vocab_items add column level varchar(40);
alter table vocab_items add column synonyms varchar(2000);
alter table vocab_items add column antonyms varchar(2000);
alter table vocab_items add column collocations varchar(2000);
alter table vocab_items add column enriched_at timestamp;

create table enrichment_jobs (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    deck_id bigint,
    vocab_item_id bigint,
    status varchar(30) not null,
    total_items integer not null,
    processed_items integer not null,
    failed_items integer not null,
    error_message varchar(1000),
    created_at timestamp not null,
    updated_at timestamp not null,
    completed_at timestamp,
    constraint fk_enrichment_jobs_owner foreign key (owner_id) references app_users(id) on delete cascade,
    constraint fk_enrichment_jobs_deck foreign key (deck_id) references decks(id) on delete cascade,
    constraint fk_enrichment_jobs_vocab_item foreign key (vocab_item_id) references vocab_items(id) on delete cascade
);

create index idx_enrichment_jobs_owner_id on enrichment_jobs(owner_id);
create index idx_enrichment_jobs_deck_id on enrichment_jobs(deck_id);
