create table questions (
    id bigint generated by default as identity primary key,
    deck_id bigint not null,
    vocab_item_id bigint not null,
    owner_id bigint not null,
    type varchar(40) not null,
    prompt varchar(1000) not null,
    correct_answer varchar(1000) not null,
    options_json varchar(4000),
    explanation varchar(1500),
    created_at timestamp not null,
    constraint fk_questions_deck foreign key (deck_id) references decks(id) on delete cascade,
    constraint fk_questions_vocab_item foreign key (vocab_item_id) references vocab_items(id) on delete cascade,
    constraint fk_questions_owner foreign key (owner_id) references app_users(id) on delete cascade
);

create table quiz_attempts (
    id bigint generated by default as identity primary key,
    deck_id bigint not null,
    user_id bigint not null,
    total_questions integer not null,
    correct_count integer not null default 0,
    completed_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_quiz_attempts_deck foreign key (deck_id) references decks(id) on delete cascade,
    constraint fk_quiz_attempts_user foreign key (user_id) references app_users(id) on delete cascade
);

create table quiz_answers (
    id bigint generated by default as identity primary key,
    attempt_id bigint not null,
    question_id bigint not null,
    answer varchar(1000),
    correct boolean not null,
    answered_at timestamp not null,
    constraint fk_quiz_answers_attempt foreign key (attempt_id) references quiz_attempts(id) on delete cascade,
    constraint fk_quiz_answers_question foreign key (question_id) references questions(id) on delete cascade,
    constraint uq_quiz_answers_attempt_question unique (attempt_id, question_id)
);

create index idx_questions_deck_id on questions(deck_id);
create index idx_questions_owner_id on questions(owner_id);
create index idx_quiz_attempts_user_id on quiz_attempts(user_id);
create index idx_quiz_answers_attempt_id on quiz_answers(attempt_id);
