create table learn_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    deck_id bigint not null,
    scope varchar(30) not null,
    total_terms integer not null,
    mastered_terms integer not null,
    total_answers integer not null,
    correct_answers integer not null,
    status varchar(30) not null,
    started_at timestamp not null,
    completed_at timestamp,
    duration_ms bigint not null default 0,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_learn_sessions_user foreign key (user_id) references app_users(id) on delete cascade,
    constraint fk_learn_sessions_deck foreign key (deck_id) references decks(id) on delete cascade
);

create table learn_session_items (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    vocab_item_id bigint not null,
    stage varchar(30) not null,
    correct_streak integer not null default 0,
    total_attempts integer not null default 0,
    correct_attempts integer not null default 0,
    incorrect_attempts integer not null default 0,
    last_answered_at timestamp,
    priority integer not null default 0,
    constraint fk_learn_session_items_session foreign key (session_id) references learn_sessions(id) on delete cascade,
    constraint fk_learn_session_items_vocab_item foreign key (vocab_item_id) references vocab_items(id) on delete cascade,
    constraint uq_learn_session_items_session_vocab unique (session_id, vocab_item_id)
);

create table learn_answers (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    session_item_id bigint not null,
    question_type varchar(30) not null,
    prompt varchar(1000) not null,
    user_answer varchar(1000),
    correct_answer varchar(1000) not null,
    correct boolean not null,
    response_time_ms bigint,
    answered_at timestamp not null,
    constraint fk_learn_answers_session foreign key (session_id) references learn_sessions(id) on delete cascade,
    constraint fk_learn_answers_item foreign key (session_item_id) references learn_session_items(id) on delete cascade
);

create index idx_learn_sessions_user_id on learn_sessions(user_id);
create index idx_learn_sessions_deck_id on learn_sessions(deck_id);
create index idx_learn_session_items_session_id on learn_session_items(session_id);
create index idx_learn_answers_session_id on learn_answers(session_id);
